development:
  # Change this values using random values or the output executing 'rake secret'.
  security: 
    secret_key_base: "CHANGEME"
    secret_key_devise: "CHANGEME"
    # A change in Devise's pepper can invalidate all your user's passwords
    pepper_devise: "CHANGEME"
  app:
    # Your domain, without protocol (only host:port)
    domain: "localhost:3000" 
    # Use SSL? (connections and cookies)
    use_ssl: false 
    # Time zone (run 'rake time:zones:all' to view all available)
    time_zone: "Madrid"
    # Default language for users
    default_language: "en"
    # Assets host WITH PROTOCOL (the same domain used above if you don't use CDNs)
    assets_host: "http://localhost:3000"
  redis:
    # Your redis host
    host: "localhost"
    # Redis listening port (default: 6379)
    port: 6379
    # Number od the DB
    db: 12
    # Namespace to use
    namespace: "watchr_development"

  unicorn:
    # Number of working processes
    working_processes: 4
    # Timeout per worker
    timeout: 30
    # User to execute the server
    user: 'ruby_user'
    # Group to execute the server
    group: 'ruby_group'
    # Uses preloading to improve the start
    preload_app: true
    # The folder in which the app is located
    app_directory: "/folder/of/app"
  email:
    # Default sender for e-mails
    default_sender: "no-reply@your-company.tld"
    smtp: # SMTP configuration
      # SMTP host
      host: "smtp.your-company.tld"
      # SMTP port (default 25 for plain connections and 465 for secure connections)
      port: 465
      # Domain in case a special HELO message is needed (Google for Apps for example).
      domain: "your-company.tld"
      # Username and password in the mail service
      username: "no-reply@your-company.tld"
      password: "CHANGEME"
      # Authentication method. It can be 'plain', 'login' or 'cram_md5'
      authentication: "plain" 
      # Use encryption in the connection with SMTP (using SSL/TLS)?
      enable_ssl: false
      # Use encryption in the connection with SMTP (using STARTTLS)?
      enable_starttls: false

# Variables for production environment.
# IMPORTANT: Set this carefully (specially the security keys) because it's a basic
# security need in production environment.
# The privacy of this keys is the base of the application security.
production:
  security:
    secret_key_base: "CHANGEME"
    secret_key_devise: "CHANGEME"
    pepper_devise: "CHANGEME"
  app:
    domain: "your-company.tld" 
    use_ssl: false
    time_zone: "Madrid"
    default_language: "en"
    assets_host: "http://your-company.tld"
  redis:
    host: "localhost"
    port: 6379
    db: 12
    namespace: "watchr_production"
  unicorn:
    working_processes: 4
    timeout: 30
    user: 'ruby_user'
    group: 'ruby_group'
    preload_app: true
    app_directory: "/folder/of/app"
  email:
    default_sender: "no-reply@your-company.tld"
    smtp:
      host: "smtp.your-company.tld"
      port: 465
      domain: "your-company.tld"
      username: "no-reply@your-company.tld"
      password: "CHANGEME"
      authentication: "plain"
      enable_ssl: false
      enable_starttls: false

# Variables for test environment.
test:
  security: 
    secret_key_base: "CHANGEME"
    secret_key_devise: "CHANGEME"
    pepper_devise: "CHANGEME"
  app:
    domain: "your-company.tld" 
    use_ssl: false 
    time_zone: "Madrid" 
    default_language: "en"
    assets_host: "http://your-company.tld"
  redis:
    host: "localhost"
    port: 6379
    db: 12
    namespace: "watchr_test"
  unicorn:
    working_processes: 4
    timeout: 30
    user: 'ruby_user'
    group: 'ruby_group'
    preload_app: true
    app_directory: "/folder/of/app"
  email:
    default_sender: "no-reply@your-company.tld"
    smtp:
      host: "smtp.your-company.tld"
      port: 465
      domain: "your-company.tld"
      username: "no-reply@your-company.tld"
      password: "CHANGEME"
      authentication: "plain"
      enable_ssl: false
      enable_starttls: false