development:
  security: # Change this values using rendom values or the output executing 'rake secret'.
    secret_key_base: "CHANGEME"
    secret_key_devise: "CHANGEME"
    pepper_devise: "CHANGEME"
  app:
    domain: "localhost:3000" # Your domain, without protocol (only host:port)
    use_ssl: false # Use SSL? (connections and cookies)
    time_zone: "Madrid" # Time zone (run 'rake time:zones:all' to view all available)
    default_language: "en" # Default language for users
  email:
    default_sender: "no-reply@your-company.tld" # Default sender for e-mails
    smtp: # SMTP configuration
      host: "smtp.your-company.tld"
      port: 465
      domain: "your-company.tld" # in case a special HELO message is needed.
      username: "no-reply@your-company.tld"
      password: "CHANGEME"
      authentication: "plain" # Can be 'plain', 'login' or 'cram_md5'
      enable_tls: true # True or false to use encryption

# Variables for test environment.
test:
  security: 
    secret_key_base: "CHANGEME"
    secret_key_devise: "CHANGEME"
    pepper_devise: "CHANGEME"
  app:
    domain: "your-company.tld" 
    use_ssl: false 
    time_zone: "Madrid" 
    default_language: "en"
  email:
    default_sender: "no-reply@your-company.tld"
    smtp:
      host: "smtp.your-company.tld"
      port: 465
      domain: "your-company.tld"
      username: "no-reply@your-company.tld"
      password: "CHANGEME"
      authentication: "plain"
      enable_tls: true

# Variables for production environment.
# Set this carefully (specially the security keys) because it's a basic
# security need in production environment.
production:
  security:
    secret_key_base: "CHANGEME"
    secret_key_devise: "CHANGEME"
    pepper_devise: "CHANGEME"
  app:
    domain: "your-company.tld" 
    use_ssl: false
    time_zone: "Madrid"
    default_language: "en"
  email:
    default_sender: "no-reply@your-company.tld"
    smtp:
      host: "smtp.your-company.tld"
      port: 465
      domain: "your-company.tld"
      username: "no-reply@your-company.tld"
      password: "CHANGEME"
      authentication: "plain"
      enable_tls: true